from __future__ import annotations

import os
import time
import uuid
from pathlib import Path
from typing import Optional

import streamlit as st

from breast_cancer_detection.utils.config import OUTPUTS_DIR, UPLOADS_DIR
from breast_cancer_detection.utils.logger import get_logger

logger = get_logger("file_store")


def ensure_storage_dirs() -> None:
    """Ensure persistent upload/output folders exist."""
    os.makedirs(UPLOADS_DIR, exist_ok=True)
    os.makedirs(OUTPUTS_DIR, exist_ok=True)


def _safe_filename(name: str) -> str:
    keep = "".join(ch for ch in name if ch.isalnum() or ch in ("-", "_", "."))
    return keep or "file.bin"


def save_uploaded_file(uploaded_file, *, prefix: str = "") -> str:
    """Persist an uploaded Streamlit file to disk and return absolute path."""
    ensure_storage_dirs()
    safe_name = _safe_filename(getattr(uploaded_file, "name", "upload.bin"))
    file_id = str(uuid.uuid4())
    pref = f"{prefix}_" if prefix else ""
    file_path = Path(UPLOADS_DIR) / f"{pref}{file_id}_{safe_name}"
    try:
        with open(file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
        logger.info("Uploaded file persisted | path=%s size=%d", file_path, file_path.stat().st_size)
        return str(file_path)
    except Exception as exc:
        logger.exception("Failed to persist upload | name=%s", safe_name)
        raise RuntimeError(f"Failed to save uploaded file '{safe_name}': {exc}") from exc


def save_output_bytes(content: bytes, filename: str) -> str:
    """Persist generated bytes into outputs folder and return absolute path."""
    ensure_storage_dirs()
    safe_name = _safe_filename(filename)
    file_id = str(uuid.uuid4())
    file_path = Path(OUTPUTS_DIR) / f"{file_id}_{safe_name}"
    try:
        with open(file_path, "wb") as f:
            f.write(content)
        logger.info("Output file written | path=%s size=%d", file_path, file_path.stat().st_size)
        return str(file_path)
    except Exception as exc:
        logger.exception("Failed writing output file | filename=%s", filename)
        raise RuntimeError(f"Failed to save output file '{filename}': {exc}") from exc


def save_output_text(content: str, filename: str, encoding: str = "utf-8") -> str:
    return save_output_bytes(content.encode(encoding), filename)


@st.cache_data(show_spinner=False)
def load_file_bytes(path: str) -> bytes:
    """Cached file-bytes reader for download controls."""
    with open(path, "rb") as f:
        return f.read()


def render_download_button(file_path: Optional[str], label: str, mime: str = "application/octet-stream", key: str = "") -> None:
    if not file_path:
        st.caption(f"{label}: not available")
        return
    try:
        data = load_file_bytes(file_path)
        st.download_button(
            label=label,
            data=data,
            file_name=Path(file_path).name,
            mime=mime,
            key=key or f"download-{Path(file_path).name}",
        )
    except Exception as exc:
        logger.exception("Download render failed | path=%s", file_path)
        st.error(f"Unable to prepare download for {Path(file_path).name}: {exc}")


def cleanup_old_files(folder: str | Path, max_age: int = 86400) -> None:
    """Delete stale files older than max_age seconds."""
    target = Path(folder)
    if not target.exists():
        return
    now = time.time()
    for item in target.iterdir():
        if not item.is_file():
            continue
        try:
            if now - item.stat().st_mtime > max_age:
                item.unlink()
                logger.info("Removed stale file | path=%s", item)
        except Exception:
            logger.exception("Failed stale-file cleanup | path=%s", item)
