from __future__ import annotations

import json
import time

from breast_cancer_detection.agents.image_analyzer_agent import safe_agent_run
from breast_cancer_detection.llm.ollama_client import OllamaLLMClient
from breast_cancer_detection.llm.prompts import (
    EXPLANATION_SYSTEM_PROMPT,
    EXPLANATION_USER_PROMPT_TEMPLATE,
    REPORT_SYSTEM_PROMPT,
    REPORT_USER_PROMPT_TEMPLATE,
)
from breast_cancer_detection.utils.pipeline_logs import append_pipeline_log


def _fallback_report(state) -> str:
    r = state.get("ensemble_result") or {}
    probs = r.get("probabilities", {})
    contrib = r.get("model_contributions", {})
    xai = r.get("xai", {})
    top_features = xai.get("top_features", [])
    eff = contrib.get("efficientnet", {})
    vit = contrib.get("vit", {})
    xgb = contrib.get("xgboost", {})
    return f"""# 1. Executive Summary
Predicted class: **{r.get('prediction', 'Unknown')}** with confidence **{r.get('confidence', 0.0):.1%}**.
Risk classification is **{r.get('risk_level', 'Unknown')}** (score **{r.get('risk_score', 0):.1f}/100**).
This output is generated by a multi-model assistive pipeline and must be interpreted by a qualified clinician.

# 2. Clinical Context & Input Quality
- Input modality: image {"+ thermal matrix" if state.get('thermal_matrix_path') else "(thermal matrix not provided)"}.
- Processing chain included denoising, contrast enhancement, ROI segmentation, and deep feature extraction.
- Output quality caveat: This report is model-generated and not a definitive diagnosis.

# 3. Patient Image Analysis
Image preprocessing and segmentation were executed to focus prediction on clinically relevant regions.
The model evaluated visual morphology, texture and deep representations to estimate class probabilities.

# 4. Thermal Analysis
Thermal modality {'provided and incorporated into ensemble weighting' if state.get('thermal_matrix_path') else 'not provided; thermal branch defaulted to neutral priors'}.
When thermal input is present, asymmetry and distribution statistics influence the malignant-risk weighting.

# 5. Model-by-Model Evidence
| Model | Normal | Benign | Malignant |
|---|---:|---:|---:|
| EfficientNet | {eff.get('Normal', 0.0):.3f} | {eff.get('Benign', 0.0):.3f} | {eff.get('Malignant', 0.0):.3f} |
| ViT | {vit.get('Normal', 0.0):.3f} | {vit.get('Benign', 0.0):.3f} | {vit.get('Malignant', 0.0):.3f} |
| XGBoost Thermal | {xgb.get('Normal', 0.0):.3f} | {xgb.get('Benign', 0.0):.3f} | {xgb.get('Malignant', 0.0):.3f} |

# 6. Probability and Confidence Interpretation
- Final ensemble probabilities: Normal={probs.get('Normal', 0.0):.3f}, Benign={probs.get('Benign', 0.0):.3f}, Malignant={probs.get('Malignant', 0.0):.3f}
- Confidence indicates separation between top-ranked and competing classes.
- Reliability reflects calibration-oriented trust estimation of model confidence.

# 7. Explainability Interpretation (Grad-CAM / SHAP / LIME)
Grad-CAM localizes image regions driving class evidence.
SHAP estimates feature-level contribution magnitudes for tabular/thermal branches.
LIME provides local perturbation-based interpretability for image predictions.
Top explainability features: {", ".join(top_features) if top_features else "Not available"}.

# 8. Risk Stratification Rationale
Risk score is derived primarily from malignant-class probability and calibration scaling.
Current risk output: **{r.get('risk_level', 'Unknown')}** with score **{r.get('risk_score', 0):.1f}/100**.
This should be used as triage support rather than stand-alone clinical decisioning.

# 9. Differential Considerations
Potential overlap can occur among benign, inflammatory and malignant-like imaging patterns.
Clinical history, exam findings, and diagnostic imaging correlation are required for interpretation.

# 10. Recommended Next Clinical Actions
1. Correlate with radiologist/oncologist review.
2. Consider targeted diagnostic imaging if risk is medium/high.
3. Escalate to biopsy/pathology workflow where clinically indicated.
4. Maintain routine follow-up if low risk but symptoms persist.

# 11. Technical Appendix & Limitations
Ensemble used EfficientNet + ViT + thermal XGBoost (when available).
Model outputs depend on image quality, domain similarity to training data, and runtime compatibility.
This report is generated by an assistive AI system and is not a medical diagnosis.

    """


def _fallback_explanation(state) -> str:
    r = state.get("ensemble_result") or {}
    return (
        f"The model estimates **{r.get('prediction', 'Unknown')}** with confidence "
        f"{r.get('confidence', 0.0):.1%} and a risk score of {r.get('risk_score', 0):.1f}/100. "
        "This output is an assistive signal only, not a definitive diagnosis. "
        "Please discuss results with a qualified medical professional."
    )


@safe_agent_run
def report_generator_node(state):
    start = time.perf_counter()
    append_pipeline_log(state, "report_generator", "Preparing structured LLM report prompt")
    result = state.get("ensemble_result") or {}
    contrib = result.get("model_contributions", {})
    xgb = contrib.get("xgboost", {"Normal": 0, "Benign": 0, "Malignant": 0})
    prompt = REPORT_USER_PROMPT_TEMPLATE.format(
        prediction=result.get("prediction", "Unknown"),
        confidence=result.get("confidence", 0.0),
        risk_level=result.get("risk_level", "Unknown"),
        risk_score=result.get("risk_score", 0.0),
        eff_normal=contrib.get("efficientnet", {}).get("Normal", 0.0),
        eff_benign=contrib.get("efficientnet", {}).get("Benign", 0.0),
        eff_malignant=contrib.get("efficientnet", {}).get("Malignant", 0.0),
        vit_normal=contrib.get("vit", {}).get("Normal", 0.0),
        vit_benign=contrib.get("vit", {}).get("Benign", 0.0),
        vit_malignant=contrib.get("vit", {}).get("Malignant", 0.0),
        xgb_normal=xgb.get("Normal", 0.0),
        xgb_benign=xgb.get("Benign", 0.0),
        xgb_malignant=xgb.get("Malignant", 0.0),
        top_features=", ".join(result.get("xai", {}).get("top_features", [])),
        xai_summary="Explainability artifacts indicate model attention localization, feature attribution strength, and local contrastive evidence.",
        thermal_summary="Thermal asymmetry, hotspot burden, gradient dispersion, and entropy profile were analyzed with calibrated interpretation.",
    )
    try:
        client = OllamaLLMClient.get_shared()
        report = client.generate(prompt=prompt, system=REPORT_SYSTEM_PROMPT, temperature=0.3)
        append_pipeline_log(state, "report_generator", "Report generated with Ollama")
    except Exception:
        report = _fallback_report(state)
        append_pipeline_log(state, "report_generator", "Ollama unavailable; fallback report generated", level="WARN")
    state["markdown_report"] = report

    reasoning_payload = result.get("reasoning_payload") or {
        "prediction": result.get("prediction", "Unknown"),
        "confidence": float(result.get("confidence", 0.0)),
        "risk_score": float(result.get("risk_score", 0.0)),
        "key_features": result.get("xai", {}).get("top_features", []),
        "notes": "Model-based reasoning derived from ensemble probabilities and explainability features.",
    }
    try:
        client = OllamaLLMClient.get_shared()
        explanation_prompt = EXPLANATION_USER_PROMPT_TEMPLATE.format(payload_json=json.dumps(reasoning_payload, indent=2))
        explanation = client.generate(prompt=explanation_prompt, system=EXPLANATION_SYSTEM_PROMPT, temperature=0.2)
        append_pipeline_log(state, "report_generator", "LLM explanation generated")
    except Exception:
        explanation = _fallback_explanation(state)
        append_pipeline_log(state, "report_generator", "LLM explanation fallback used", level="WARN")

    state["llm_response"] = explanation
    if isinstance(result, dict):
        result["explanation"] = explanation
    elapsed = time.perf_counter() - start
    append_pipeline_log(state, "report_generator", "Report generation complete", details={"elapsed_s": f"{elapsed:.3f}"})
    state["processing_time"] = state.get("processing_time", 0.0) + elapsed
    return state

